/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sungcms.login;

import sungcms.register.RegisterViewTest;
import java.awt.Color;
import java.rmi.Naming;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mushmush
 */
public class LoginViewTest extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginViewTest() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JPanel();
        usernameLbl = new javax.swing.JLabel();
        passLbl = new javax.swing.JLabel();
        usernameTf = new javax.swing.JTextField();
        passPf = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        registerLbl = new javax.swing.JLabel();
        imageLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcom");
        setName("frame"); // NOI18N
        setSize(new java.awt.Dimension(1200, 675));

        pane.setPreferredSize(new java.awt.Dimension(1200, 675));

        usernameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameLbl.setText("Username");
        usernameLbl.setMaximumSize(new java.awt.Dimension(120, 22));
        usernameLbl.setMinimumSize(new java.awt.Dimension(120, 22));
        usernameLbl.setPreferredSize(new java.awt.Dimension(120, 22));

        passLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passLbl.setText("Password");
        passLbl.setMaximumSize(new java.awt.Dimension(120, 22));
        passLbl.setMinimumSize(new java.awt.Dimension(120, 22));
        passLbl.setPreferredSize(new java.awt.Dimension(120, 22));

        usernameTf.setMaximumSize(new java.awt.Dimension(270, 22));
        usernameTf.setMinimumSize(new java.awt.Dimension(270, 22));
        usernameTf.setPreferredSize(new java.awt.Dimension(270, 22));

        passPf.setMaximumSize(new java.awt.Dimension(270, 22));
        passPf.setMinimumSize(new java.awt.Dimension(270, 22));
        passPf.setPreferredSize(new java.awt.Dimension(270, 22));

        loginBtn.setText("Login");
        loginBtn.setMaximumSize(new java.awt.Dimension(85, 22));
        loginBtn.setMinimumSize(new java.awt.Dimension(85, 22));
        loginBtn.setPreferredSize(new java.awt.Dimension(85, 22));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Phosphate", 3, 24)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("SUN Grocery Management System");
        titleLbl.setMaximumSize(new java.awt.Dimension(450, 31));
        titleLbl.setMinimumSize(new java.awt.Dimension(450, 31));
        titleLbl.setPreferredSize(new java.awt.Dimension(450, 31));

        registerLbl.setForeground(new java.awt.Color(0, 102, 255));
        registerLbl.setText("Need an account? Register");
        registerLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 255)));
        registerLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerLblMouseExited(evt);
            }
        });

        imageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sungcms/image/systemIcon.png"))); // NOI18N
        imageLbl.setMaximumSize(new java.awt.Dimension(450, 324));
        imageLbl.setMinimumSize(new java.awt.Dimension(450, 324));
        imageLbl.setPreferredSize(new java.awt.Dimension(450, 324));

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneLayout.createSequentialGroup()
                        .addComponent(usernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneLayout.createSequentialGroup()
                        .addComponent(passLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passPf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titleLbl, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageLbl, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerLbl, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(loginBtn, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passPf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerLbl)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

        // TODO add your handling code here:
        String username = usernameTf.getText();
        String password = passPf.getText();
        
        boolean result = false;
        boolean usernameCheckEmpty = username.equals("");
        boolean passCheckEmpty = password.equals("");
        
        if(usernameCheckEmpty && passCheckEmpty){
            JOptionPane.showMessageDialog(null, "Form Error:\nUsername is empty! \nPassword is empty!");
        } else if (usernameCheckEmpty){
            JOptionPane.showMessageDialog(null, "Form Error:\nUsername is empty!");
        } else if (passCheckEmpty){
            JOptionPane.showMessageDialog(null, "Form Error:\nPassword is empty!");
        } else {
            JOptionPane.showMessageDialog(null, "Login Successful!");
//            try {
//                LoginRemote login = (LoginRemote)Naming.lookup("rmi://localhost:7777/login");
//                result = login.checkLogin(username, password);
//
//            } catch (Exception e){
//                e.printStackTrace();
//            }
//
//            if(!result){
//                JOptionPane.showMessageDialog(null, "Vallidation Error:\nInvalid username or password!");
//            } else {
//                JOptionPane.showMessageDialog(null, "Login successful!");
//            }
        }
        
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void registerLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLblMouseEntered
        // TODO add your handling code here:
        registerLbl.setForeground(Color.gray);
        registerLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.gray));
    }//GEN-LAST:event_registerLblMouseEntered

    private void registerLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLblMouseExited
        // TODO add your handling code here:
        registerLbl.setForeground(Color.blue);
        registerLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.blue));
    }//GEN-LAST:event_registerLblMouseExited

    private void registerLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLblMouseClicked
        // TODO add your handling code here:
        RegisterViewTest registerView = new RegisterViewTest();
        registerView.setVisible(true);
        registerView.pack();
        registerView.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_registerLblMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLbl;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel pane;
    private javax.swing.JLabel passLbl;
    private javax.swing.JPasswordField passPf;
    private javax.swing.JLabel registerLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTf;
    // End of variables declaration//GEN-END:variables
}
