/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sungcms.login;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mushmush
 */
public class RegisterView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterView
     */
    public RegisterView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JPanel();
        usernameLbl = new javax.swing.JLabel();
        passLbl = new javax.swing.JLabel();
        usernameTf = new javax.swing.JTextField();
        passPf = new javax.swing.JPasswordField();
        registerBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        loginLbl = new javax.swing.JLabel();
        confirmPassLbl = new javax.swing.JLabel();
        confirmPassPf = new javax.swing.JPasswordField();
        firstNameLbl = new javax.swing.JLabel();
        firstNameTf = new javax.swing.JTextField();
        lastNameLbl = new javax.swing.JLabel();
        lastNameTf = new javax.swing.JTextField();
        identityLbl = new javax.swing.JLabel();
        identityTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 675));
        setSize(new java.awt.Dimension(1200, 675));

        pane.setMaximumSize(new java.awt.Dimension(1200, 675));
        pane.setMinimumSize(new java.awt.Dimension(1200, 675));
        pane.setPreferredSize(new java.awt.Dimension(1200, 675));

        usernameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameLbl.setText("Username");
        usernameLbl.setMaximumSize(new java.awt.Dimension(120, 22));
        usernameLbl.setMinimumSize(new java.awt.Dimension(120, 22));
        usernameLbl.setPreferredSize(new java.awt.Dimension(120, 22));

        passLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passLbl.setText("Password");
        passLbl.setMaximumSize(new java.awt.Dimension(120, 22));
        passLbl.setMinimumSize(new java.awt.Dimension(120, 22));
        passLbl.setPreferredSize(new java.awt.Dimension(120, 22));

        usernameTf.setMaximumSize(new java.awt.Dimension(270, 22));
        usernameTf.setMinimumSize(new java.awt.Dimension(270, 22));
        usernameTf.setPreferredSize(new java.awt.Dimension(270, 22));
        usernameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTfActionPerformed(evt);
            }
        });

        passPf.setMaximumSize(new java.awt.Dimension(270, 22));
        passPf.setMinimumSize(new java.awt.Dimension(270, 22));
        passPf.setPreferredSize(new java.awt.Dimension(270, 22));

        registerBtn.setText("Register");
        registerBtn.setMaximumSize(new java.awt.Dimension(85, 22));
        registerBtn.setMinimumSize(new java.awt.Dimension(85, 22));
        registerBtn.setPreferredSize(new java.awt.Dimension(85, 22));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Phosphate", 3, 24)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Registration");
        titleLbl.setMaximumSize(new java.awt.Dimension(450, 31));
        titleLbl.setMinimumSize(new java.awt.Dimension(450, 31));
        titleLbl.setPreferredSize(new java.awt.Dimension(450, 31));

        loginLbl.setForeground(new java.awt.Color(0, 102, 255));
        loginLbl.setText("Already have an account? Login");
        loginLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 255)));
        loginLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginLblMouseExited(evt);
            }
        });

        confirmPassLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        confirmPassLbl.setText("Confrim Password");
        confirmPassLbl.setMaximumSize(new java.awt.Dimension(120, 22));
        confirmPassLbl.setMinimumSize(new java.awt.Dimension(120, 22));
        confirmPassLbl.setPreferredSize(new java.awt.Dimension(120, 22));

        confirmPassPf.setMaximumSize(new java.awt.Dimension(270, 22));
        confirmPassPf.setMinimumSize(new java.awt.Dimension(270, 22));
        confirmPassPf.setPreferredSize(new java.awt.Dimension(270, 22));

        firstNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstNameLbl.setText("First Name");
        firstNameLbl.setMaximumSize(new java.awt.Dimension(120, 22));
        firstNameLbl.setMinimumSize(new java.awt.Dimension(120, 22));
        firstNameLbl.setPreferredSize(new java.awt.Dimension(120, 22));

        firstNameTf.setMaximumSize(new java.awt.Dimension(270, 22));
        firstNameTf.setMinimumSize(new java.awt.Dimension(270, 22));
        firstNameTf.setPreferredSize(new java.awt.Dimension(270, 22));
        firstNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTfActionPerformed(evt);
            }
        });

        lastNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastNameLbl.setText("Last Name");
        lastNameLbl.setMaximumSize(new java.awt.Dimension(120, 22));
        lastNameLbl.setMinimumSize(new java.awt.Dimension(120, 22));
        lastNameLbl.setPreferredSize(new java.awt.Dimension(120, 22));

        lastNameTf.setMaximumSize(new java.awt.Dimension(270, 22));
        lastNameTf.setMinimumSize(new java.awt.Dimension(270, 22));
        lastNameTf.setPreferredSize(new java.awt.Dimension(270, 22));
        lastNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTfActionPerformed(evt);
            }
        });

        identityLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        identityLbl.setText("IC/Passport No");
        identityLbl.setMaximumSize(new java.awt.Dimension(120, 22));
        identityLbl.setMinimumSize(new java.awt.Dimension(120, 22));
        identityLbl.setPreferredSize(new java.awt.Dimension(120, 22));

        identityTf.setMaximumSize(new java.awt.Dimension(270, 22));
        identityTf.setMinimumSize(new java.awt.Dimension(270, 22));
        identityTf.setPreferredSize(new java.awt.Dimension(270, 22));
        identityTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identityTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneLayout.createSequentialGroup()
                        .addComponent(usernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneLayout.createSequentialGroup()
                        .addComponent(firstNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(firstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneLayout.createSequentialGroup()
                        .addComponent(lastNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneLayout.createSequentialGroup()
                        .addComponent(identityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(identityTf, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneLayout.createSequentialGroup()
                        .addComponent(passLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passPf, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneLayout.createSequentialGroup()
                        .addComponent(confirmPassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(confirmPassPf, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(registerBtn, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLbl, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginLbl, javax.swing.GroupLayout.Alignment.CENTER))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passPf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPassPf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginLbl)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTfActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        String username = usernameTf.getText();
        String firstName = firstNameTf.getText();
        String lastName = lastNameTf.getText();
        
        String password = passPf.getText();
        String confirmPassword = confirmPassPf.getText();
        
        if(!password.equals(confirmPassword)){
            JOptionPane.showMessageDialog(null, "Password is not tally!");
        } else {
            JOptionPane.showMessageDialog(null, "Password checked!");
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void loginLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLblMouseClicked
        // TODO add your handling code here:
        LoginView loginView= new LoginView();
        loginView.setVisible(true);
        loginView.pack();
        loginView.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_loginLblMouseClicked

    private void loginLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLblMouseEntered
        // TODO add your handling code here:
        loginLbl.setForeground(Color.gray);
        loginLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.gray));
    }//GEN-LAST:event_loginLblMouseEntered

    private void loginLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLblMouseExited
        // TODO add your handling code here:
        loginLbl.setForeground(Color.blue);
        loginLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.blue));
    }//GEN-LAST:event_loginLblMouseExited

    private void firstNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTfActionPerformed

    private void lastNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTfActionPerformed

    private void identityTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identityTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identityTfActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmPassLbl;
    private javax.swing.JPasswordField confirmPassPf;
    private javax.swing.JLabel firstNameLbl;
    private javax.swing.JTextField firstNameTf;
    private javax.swing.JLabel identityLbl;
    private javax.swing.JTextField identityTf;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JTextField lastNameTf;
    private javax.swing.JLabel loginLbl;
    private javax.swing.JPanel pane;
    private javax.swing.JLabel passLbl;
    private javax.swing.JPasswordField passPf;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTf;
    // End of variables declaration//GEN-END:variables
}
