/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sungcms.dashboard;

import java.awt.Component;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author mushmush
 */
public class DashboardViewTest extends javax.swing.JFrame {

    /**
     * Creates new form DashboardView
     */
    public DashboardViewTest() {
        initComponents();
        Component [] components = this.getContentPane().getComponents();
        
        for(Component component : components){
            if(component instanceof JButton){
                ((JButton) component).setUI(new BasicButtonUI());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPane = new javax.swing.JPanel();
        iconPane = new javax.swing.JPanel();
        groceryMenu = new javax.swing.JButton();
        categoryMenu = new javax.swing.JButton();
        supplierMenu = new javax.swing.JButton();
        salesMenu = new javax.swing.JButton();
        contentPane = new javax.swing.JLayeredPane();
        groceryView = new javax.swing.JPanel();
        productView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame"); // NOI18N
        setSize(new java.awt.Dimension(1200, 675));

        menuPane.setBackground(new java.awt.Color(153, 153, 153));
        menuPane.setForeground(new java.awt.Color(153, 153, 153));

        iconPane.setBackground(new java.awt.Color(153, 153, 153));
        iconPane.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout iconPaneLayout = new javax.swing.GroupLayout(iconPane);
        iconPane.setLayout(iconPaneLayout);
        iconPaneLayout.setHorizontalGroup(
            iconPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        iconPaneLayout.setVerticalGroup(
            iconPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        menuPane.add(iconPane);

        groceryMenu.setText("Grocery");
        groceryMenu.setAlignmentY(0.0F);
        groceryMenu.setMaximumSize(new java.awt.Dimension(250, 50));
        groceryMenu.setMinimumSize(new java.awt.Dimension(250, 50));
        groceryMenu.setPreferredSize(new java.awt.Dimension(250, 50));
        menuPane.add(groceryMenu);

        categoryMenu.setText("Category");
        categoryMenu.setAlignmentY(0.0F);
        categoryMenu.setMaximumSize(new java.awt.Dimension(250, 50));
        categoryMenu.setMinimumSize(new java.awt.Dimension(250, 50));
        categoryMenu.setPreferredSize(new java.awt.Dimension(250, 50));
        menuPane.add(categoryMenu);

        supplierMenu.setText("Supplier");
        supplierMenu.setAlignmentY(0.0F);
        supplierMenu.setMaximumSize(new java.awt.Dimension(250, 50));
        supplierMenu.setMinimumSize(new java.awt.Dimension(250, 50));
        supplierMenu.setPreferredSize(new java.awt.Dimension(250, 50));
        menuPane.add(supplierMenu);

        salesMenu.setText("Sales Executives");
        salesMenu.setAlignmentY(0.0F);
        salesMenu.setMaximumSize(new java.awt.Dimension(250, 50));
        salesMenu.setMinimumSize(new java.awt.Dimension(250, 50));
        salesMenu.setPreferredSize(new java.awt.Dimension(250, 50));
        menuPane.add(salesMenu);

        groceryView.setAlignmentX(0.0F);
        groceryView.setAlignmentY(0.0F);

        javax.swing.GroupLayout groceryViewLayout = new javax.swing.GroupLayout(groceryView);
        groceryView.setLayout(groceryViewLayout);
        groceryViewLayout.setHorizontalGroup(
            groceryViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1002, Short.MAX_VALUE)
        );
        groceryViewLayout.setVerticalGroup(
            groceryViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout productViewLayout = new javax.swing.GroupLayout(productView);
        productView.setLayout(productViewLayout);
        productViewLayout.setHorizontalGroup(
            productViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 986, Short.MAX_VALUE)
        );
        productViewLayout.setVerticalGroup(
            productViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        contentPane.setLayer(groceryView, javax.swing.JLayeredPane.DEFAULT_LAYER);
        contentPane.setLayer(productView, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groceryView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(productView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groceryView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(productView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPane, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPane, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
            .addComponent(contentPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardViewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardViewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardViewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardViewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardViewTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton categoryMenu;
    private javax.swing.JLayeredPane contentPane;
    private javax.swing.JButton groceryMenu;
    private javax.swing.JPanel groceryView;
    private javax.swing.JPanel iconPane;
    private javax.swing.JPanel menuPane;
    private javax.swing.JPanel productView;
    private javax.swing.JButton salesMenu;
    private javax.swing.JButton supplierMenu;
    // End of variables declaration//GEN-END:variables
}
